### ISSUE TITLE
cannot import module

### ISSUE THREAD

**Issue by Monique497** [tvst/st-annotated-text#1]
Hi,

I have st-annotated-text installed using pip, but I cannot import the module as described in your readme-file.

This is what I get when I enter _**pip show st-annotated-text**_:

Name: st-annotated-text
Version: 1.0.1
Summary: A simple component to display annotated text in Streamlit apps.
Home-page: https://github.com/tvst/st-annotated-text
Author: Thiago Teixeira
Author-email: me@thiagot.com
License: Apache 2
Location: /home/monique/anaconda3/envs/ta/lib/python3.6/site-packages
Requires: htbuilder
Required-by: 

So, everything looks good. 

However, when I then say:
_from st_annotated_text import annotated_text_

It gives me the module not found-error.
I was trying to figure out what the package name should be, but no luck, since I am not that hardcore python-developer.

Perhaps there is an easy solution.

**Comment by mart1nro** [comment]
Had the same problem.
Importing it using
`from annotated_text import annotated_text`
works.

**Comment by Monique497** [comment]
Thank you, that worked!
