### ISSUE TITLE
Feature Request - Auto Anno text if marked

### ISSUE THREAD

**Issue by ChrisDelClea** [tvst/st-annotated-text#10]
Is it possible to extend this component so that if I mark I word with my courser, 
it gets automatically annotated by the class I chose in advance? 
Just an ide I wanted to share. I'd really much like it.

**Comment by tvst** [comment]
Hi @ChrisChross , thanks for posting. I don't really understand the idea, though. Can you provide some more information?

**Comment by ChrisDelClea** [comment]
Hi @tvst ,
you can check https://prodi.gy/demo.
The idea is simple: you choose a label or class e.g. Person and than click on the person's name in the text.
Consecutive the text gets marked with the label.

**Comment by ChrisDelClea** [comment]
If possible reopen this :)
