### ISSUE TITLE
Enable fullscreen botton

### ISSUE THREAD

**Issue by roberto-cadili** [tvst/st-annotated-text#11]
Hi there, many thanks for this very nice component!

I was wondering if it's possible to include a "fullscreen" botton like in many other streamlite native visualizations. If so, how?

Modifying the height is okayish but not optimal if the text is very long.

Many thanks to anyone who can help!

Cheers

**Comment by tvst** [comment]
This is not really possible today with Streamlit, except with some nasty hacks. I'll add the idea to Streamlit's internal roadmap, though!
