### ISSUE TITLE
How would I submit a list of tuples?

### ISSUE THREAD

**Issue by dorealex** [tvst/st-annotated-text#12]
Using spacy to get part of speech tagging, and essentially emulating displacy I built myself a quick annotation getting function:

`def get_annotations(text):
    result = []
    d = {
        'ADJ':'#7FFFD4',
        'PROPN':'#7FFF00',
        'AUX':'#9932CC',
        'VERB':'#556B2F',
        'NOUN':'#BDB76B'
    }
    k = set(list(d.keys()))
    doc = nlp(text)
    for x in doc:
        token = ""
        if x.pos_ in k:
            token = (x.text, x.pos_, d.get(x.pos_))
        else:
            token = x.text
        
        result.append(token)
    return tuple(result)
`

My issue comes up when submitting the result to annotated_text(). In fact, if I save the example's sample text to a variable I get an oh noes error. Is there any way of passing a tuple of tuples or a list of tuples?

**Comment by dorealex** [comment]
Found the answer, silly me.

For example:
`my_list = ['My', ('dog', 'Friend', 'green'), 'barked at the',('robber', 'Foe', 'red')]
annotated_text(*my_list)
`
![Screenshot from 2021-04-11 23-40-34](https://user-images.githubusercontent.com/29454962/114337576-578bc000-9b1f-11eb-9eed-d861cb840f23.png)

**Comment by tvst** [comment]
Glad you figured it out! Closing
