### ISSUE TITLE
Dark Mode support

### ISSUE THREAD

**Issue by philippedeb** [tvst/st-annotated-text#13]
Streamlit applications using this component are not properly visible when preferring Dark Mode or have it set as system default.

### Light Mode
![st_annotated_text_light_mode](https://user-images.githubusercontent.com/56686692/116818215-89b29f80-ab6a-11eb-90fb-df6a86321f4a.JPG)

### Dark Mode
![st_annotated_text_dark_mode](https://user-images.githubusercontent.com/56686692/116818218-8d462680-ab6a-11eb-886f-097c241b1d88.JPG)

The non-highlighted text colors should inherit from the current Theme (Light/Dark/Custom).

**Comment by belma-ibrahimovic** [comment]
Any news regarding this issue?

**Comment by tvst** [comment]
This is supported now, since 2.0 was released yesterday. Closing
