### ISSUE TITLE
streamlit themes support

### ISSUE THREAD

**Issue by munivinayk** [tvst/st-annotated-text#17]
Hi,

I am currently using streamlit themes and trying to display annoated text and it always shows the text in black. Please see the sample below for your reference. Kindly guide me in resolving this issue.

![Screenshot 2021-08-30 at 6 23 05 PM](https://user-images.githubusercontent.com/26641033/131325299-6eb1d092-3037-49fd-83ba-ddd99e1bc9aa.png)

**Comment by tvst** [comment]
Hey, can you check which version of st-annotated-text are you using? Version 2.0.0 should support themes, since it just uses Streamlit's st.markdown behind the scenes.
