### ISSUE TITLE
Option to provide height of the iframe

### ISSUE THREAD

**Issue by jithurjacob** [tvst/st-annotated-text#3]
Please provide an option to set the height of the output iframe. https://docs.streamlit.io/en/stable/develop_streamlit_components.html#streamlit.components.v1.html

**Comment by ChrisDelClea** [comment]
I strongly support the upper idea. It seems to be very limited in space. About 4 rows.

**Comment by mataney** [comment]
This should do the trick
https://github.com/tvst/st-annotated-text/pull/7

**Comment by tvst** [comment]
Merged.

**Comment by srikar3120** [comment]
Hi @tvst , Im using below code to annotate sentence

def annotate_answer(answer, context):
    start_idx = context.find(answer)
    end_idx = start_idx + len(answer)
    # calculate dynamic height depending on context length
    height = int(len(context) * 0.25) + 5
    annotated_text(context[:start_idx], (answer, "Moderate", "#8ef"), context[end_idx:], height=height)

   if (row["label"] == 1):
      # s is sentence here that i want to annotate
       annotate_answer(s, s) 

context Im passing is full sentence. And I want to annotate full sentence.
Im seeing it getting annotated but there is gap between the sentences after annotation and sometimes not able to some of the text if the sentence is too big. Can you please let me know how to caluculate dynamically [height?]
I tried to play with height parameter in the method but no luck... If I reduce height, lines are missing... If I increase height, space after the line is too big

![image](https://user-images.githubusercontent.com/87526089/125936891-a7b64fa8-749e-458e-a795-e12685e78b00.png)
![image](https://user-images.githubusercontent.com/87526089/125936919-b9062d64-bbfe-4c7b-bd2f-6d721d30a7aa.png)
